db:
  username: ${username.value:postgres}
  password: pass
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0
  properties:
    first: 123
    second: 567
    third.value: Third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3
spring.profiles.active: qa

logging:
  level:
    root: INFO
    com.barabanov.spring.database.pool.ConnectionPool: INFO
    org.springframework.jdbc.core: TRACE
  file:
    name: barabanov.log
    path: /
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    format:
      date: iso
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres_spring
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 176389550094-taa89a6n0j5047ik8iemq7n6d1pqld65.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: openid, email, profile #по умолчанию будет openid, а про email и т.д. - хз